# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20170823_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='thumnails',
            new_name='thumbnail',
        ),
    ]
