# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('company', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('thumnails', models.URLField()),
                ('rating', models.FloatField(default=3.0)),
                ('store_url', models.URLField()),
                ('last_update_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Thumnails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='des_thumnails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thumnails'),
        ),
        migrations.AddField(
            model_name='app',
            name='language',
            field=models.ManyToManyField(to='app.Languages'),
        ),
    ]
