# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumnails',
            field=models.CharField(max_length=100),
        ),
    ]
